# Generated by Django 3.2.12 on 2024-02-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
