# Generated by Django 3.2.12 on 2024-02-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_expense_category'),
        ('category', '0002_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Expense_Category',
        ),
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Expense_SubCategory',
        ),
    ]
