# Generated by Django 3.2.12 on 2024-02-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_expense_category'),
        ('category', '0003_auto_20240210_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense_Category',
            new_name='ExpenseCategory',
        ),
    ]
