# Generated by Django 5.0.4 on 2024-05-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_incomecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.expensecategory')),
            ],
        ),
    ]
