# Generated by Django 5.0.4 on 2024-05-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_expensecompanies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecompanies',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='expensecompanies',
            name='categories',
            field=models.ManyToManyField(to='category.expensecategory'),
        ),
    ]
