# Generated by Django 3.2.12 on 2024-01-15 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20240115_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='methodofpayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.methodofpayment'),
        ),
    ]
