# Generated by Django 3.2.12 on 2024-02-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0006_incomecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodOfIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.incomecategory')),
                ('methodofincome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.methodofincome', verbose_name='Method of income')),
            ],
        ),
    ]
